USE master;
GO
CREATE MASTER KEY ENCRYPTION BY PASSWORD='P@ssw0rd';
GO
CREATE CERTIFICATE TdeCertificate WITH SUBJECT='TDE Certificate'
GO
USE [AZ-DB-TEST-BASIC];
GO
CREATE DATABASE ENCRYPTION KEY
WITH ALGORITHM = AES_128
ENCRTYPTION BY SERVER CERTIFICATE TdeCertificate;
GO
ALTER DATABASE [AZ-DB-TEST-BASIC]
SET ENCRYPTION ON;
GO
