USE master;
GO
CREATE MASTER KEY ENCRYPTION BY PASSWORD='<Password>'
GO
CREATE CERTIFICATE TdeCertificate WITH SUBJECT='TDE Certificate'
GO
USE YourDbName
GO
CREATE DATABASE ENCRYPTION KEY
WITH ALGORITM = AES_128
ENCRTYPTION BY SERVER CERTIFICATE TdeCertificate;
GO
ALTER DATABASE YourDbName
SET ENCRYPTION ON;
GO
