-- Generate table with X columns and Y rows filled in with GUIDS
DECLARE @NUMBER_OF_COLUNNS AS INT
DECLARE @NUMBER_OF_ROWS AS INT
DECLARE @COUNTER AS INT
DECLARE @QUERY AS VARCHAR(MAX)

SET @NUMBER_OF_COLUNNS=8
SET @NUMBER_OF_ROWS=399990
-- Create table with specified @NUMBER_OF_COLUNNS
SET @COUNTER=1
SET @QUERY = 'IF OBJECT_ID(N''dbo.TestTable'', N''U'') IS NULL CREATE TABLE TestTable ('
WHILE(@COUNTER<=@NUMBER_OF_COLUNNS)
	BEGIN
	SET @QUERY = @QUERY + 'Column' + CAST(@COUNTER as varchar(max)) + ' UNIQUEIDENTIFIER, '
	SET @COUNTER = @COUNTER + 1
	END
SET @QUERY = @QUERY + ');'
EXEC (@QUERY)
-- Generate specified @NUMBER_OF_ROWS
SET @COUNTER=0
SET @QUERY=''
SET @QUERY = 'IF OBJECT_ID(N''dbo.TestTable'', N''U'') IS NOT NULL INSERT INTO TestTable VALUES ('
WHILE(@COUNTER<=@NUMBER_OF_COLUNNS-1)
	BEGIN
	SET @QUERY = @QUERY + 'NEWID(), '
	SET @COUNTER = @COUNTER + 1
	END
SET @QUERY = @QUERY + ' NEWID());'

SET @COUNTER = 1
WHILE(@COUNTER<=@NUMBER_OF_ROWS)
	BEGIN
	EXEC (@QUERY)
	SET @COUNTER = @COUNTER + 1
	END
